---
title: "A Brief Intro to Databases"
author: "Ted Laderas"
date: "`r Sys.Date()`"
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: xaringan-themer.css
    nature:
      ratio: '16:9'
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
library(xaringanthemer)
mono_light(
  base_color = "midnightblue",
  header_font_google = google_font("Josefin Sans"),
  text_font_google   = google_font("Montserrat", "300", "300i"),
  code_font_google   = google_font("Droid Mono"),
  link_color = "deepskyblue1",
  text_font_size = "28px"
)
```
class: center, middle

# Disclaimer: I got a C in the Database Course
## (Now I teach them)

---
# What is a Database?

A collection of data organized in a way that can be easily accessed, managed, and updated

---
# Flat Files/Tables

A database can be simple as a collection of flat files

- organized in a file system
- specific programs to access/update

---
# Flat Files/Tables have Disadvantages

Any ideas?

-- 
- lack of access control/security
- lack of data integrity (did we both update a table at once?)
- lack of quick access to the specific data

---
# Database Management Systems (DBMS)

Software that allows for the creation, defintion, and manipulation of data in the database

- accommodates large datasets (storage and querying)
- ensures data integrity when multiple users are accessing/modifying it at once3
- crash recovery, logging
- security and access control

---
# Relational Data Model



---
# Structured Query Language


---
# Structured Query Language example

---
